/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.codeengine.studentmanagement.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the School service. Represents a row in the &quot;GB_School&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.codeengine.studentmanagement.model.impl.SchoolModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.codeengine.studentmanagement.model.impl.SchoolImpl}.
 * </p>
 *
 * @author ces
 * @see School
 * @see com.codeengine.studentmanagement.model.impl.SchoolImpl
 * @see com.codeengine.studentmanagement.model.impl.SchoolModelImpl
 * @generated
 */
public interface SchoolModel extends BaseModel<School> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a school model instance should use the {@link School} interface instead.
	 */

	/**
	 * Returns the primary key of this school.
	 *
	 * @return the primary key of this school
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this school.
	 *
	 * @param primaryKey the primary key of this school
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this school.
	 *
	 * @return the uuid of this school
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this school.
	 *
	 * @param uuid the uuid of this school
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the school ID of this school.
	 *
	 * @return the school ID of this school
	 */
	public long getSchoolId();

	/**
	 * Sets the school ID of this school.
	 *
	 * @param schoolId the school ID of this school
	 */
	public void setSchoolId(long schoolId);

	/**
	 * Returns the school name of this school.
	 *
	 * @return the school name of this school
	 */
	@AutoEscape
	public String getSchoolName();

	/**
	 * Sets the school name of this school.
	 *
	 * @param schoolName the school name of this school
	 */
	public void setSchoolName(String schoolName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.codeengine.studentmanagement.model.School school);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.codeengine.studentmanagement.model.School> toCacheModel();

	@Override
	public com.codeengine.studentmanagement.model.School toEscapedModel();

	@Override
	public com.codeengine.studentmanagement.model.School toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}