/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.codeengine.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Clazz service. Represents a row in the &quot;GB_Clazz&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.codeengine.service.model.impl.ClazzModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.codeengine.service.model.impl.ClazzImpl}.
 * </p>
 *
 * @author ces
 * @see Clazz
 * @see com.codeengine.service.model.impl.ClazzImpl
 * @see com.codeengine.service.model.impl.ClazzModelImpl
 * @generated
 */
public interface ClazzModel extends BaseModel<Clazz> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a clazz model instance should use the {@link Clazz} interface instead.
	 */

	/**
	 * Returns the primary key of this clazz.
	 *
	 * @return the primary key of this clazz
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this clazz.
	 *
	 * @param primaryKey the primary key of this clazz
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this clazz.
	 *
	 * @return the uuid of this clazz
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this clazz.
	 *
	 * @param uuid the uuid of this clazz
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the clazz ID of this clazz.
	 *
	 * @return the clazz ID of this clazz
	 */
	public long getClazzId();

	/**
	 * Sets the clazz ID of this clazz.
	 *
	 * @param clazzId the clazz ID of this clazz
	 */
	public void setClazzId(long clazzId);

	/**
	 * Returns the clazz name of this clazz.
	 *
	 * @return the clazz name of this clazz
	 */
	@AutoEscape
	public String getClazzName();

	/**
	 * Sets the clazz name of this clazz.
	 *
	 * @param clazzName the clazz name of this clazz
	 */
	public void setClazzName(String clazzName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.codeengine.service.model.Clazz clazz);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.codeengine.service.model.Clazz> toCacheModel();

	@Override
	public com.codeengine.service.model.Clazz toEscapedModel();

	@Override
	public com.codeengine.service.model.Clazz toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}